version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel_network
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: nginx_webserver
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - laravel_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    networks:
      - laravel_network
    volumes:
      - dbdata:/var/lib/mysql

networks:
  laravel_network:

volumes:
  dbdata:
